### PR TITLE
fix reactor compilation

### PR DESCRIPTION
**Pull request by bam241**
I can't get it to compile, I have some linking issues with the unit test... but it does fix the compilation from the reactor.

I think you added some modification from an other branch here...

### CODE REVIEW

**Comment by jbae11** [comment]
I cloned your `fix` branch and i got it to build and run an example input file (not the `example.xml`). I noticed that the issue with the unit test arose with the recent commits on cycamore..?

**Comment by bam241** [comment]
@jbae11 I am not sure it does matter to much.

the goal of keeping those files are just to make sure, CI-hook and test are working properly.

**Comment by jbae11** [comment]
@bam241  so should I merge this and make a PR to `cyclus/recycle`?

**Comment by bam241** [comment]
That's what I pictured, unless you see any problem with my modification

**Comment by jbae11** [comment]
Nope! Will do!

**Pull request merged**
